website_url = "https://diablo.discordgamepass.com/"

[bot]
prefixes = ["dh!", "dh", "Dh", "Dh!", "dH!", "dH", "DH!", "DH"]
description = """Diablo Devils Hunt - A Game Pass Original"""
playing = "Devils are everywhere"
commands_are_case_insensitive = true

[database]
# A postgreSQL database to store information about users, channels, and guilds
# Please ensure the database exist before loading the database modules
# Quick Start : https://medium.com/coding-blocks/creating-user-database-and-adding-access-on-postgresql-8bfcd2f4a91e
enable = true
host = ""
port = ""
user = ""
password = ""
database = ""

[duckhunt_public_log]
server_id = 1013868971549794415
channel_id = 1031014591511154738

[auth.discord]
# Your bot token. You can find it on the Bot page of the Developper portal
token = ""

[cogs]
# Names of cogs to load. Usually cogs.file_name_without_py
# bots_list_and_voting must be loaded before rest_api
cogs_to_load = ['cogs.error_handling',
                'cogs.emergencies',
                'cogs.monitoring',
                'cogs.tags',
                'cogs.simple_commands',
                'cogs.background_loop',
                'cogs.support_server_commands',
                'cogs.settings_commands',
                'cogs.ducks_spawning_commands',
                'cogs.ducks_spawning',
                'cogs.ducks_hunting_commands',
                'cogs.statistics_experience_commands',
                'cogs.community',
                'cogs.private_messages_support',
                'cogs.random_ducks',
                'cogs.inventory_commands',
                'cogs.shopping_commands',
                'cogs.duck_boss',
                'cogs.prestige_commands',
                'cogs.bots_list_and_voting',
                'cogs.landmines',
                'cogs.rest_api',
                'cogs.buttons',
                'cogs.help_command',
                'jishaku',
                ]
# The name after cogs is the name of the class
[cogs.SimpleCommands]
wiki_url = "https://diablo.discordgamepass.com"

[cogs.DuckBoss]
boss_channel_id = 1031014088010113084
required_bangs = 40
role_ping_id = 1031013477969563688


[cogs.SupportServerCommands]
# That's the ID of your server where the command will be ran
support_server_id = 1013868971549794415
# ID of an empty channel that will be used as a status dashboard.
status_channel_id = 1031023854753153024

[cogs.Community]
servers = [1013868971549794415]
rpg_role_name = "Hunter License"
moderators_that_can_delete_with_reactions = [1015526330814697542]

[cogs.PrivateMessagesSupport]
forwarding_category = 1016854290519834694

[cogs.RestAPI]
listen_ip = "0.0.0.0"
listen_port = "8080"
route_prefix = "/api"
# Access keys are actually GUIDs/UUIDs.
# You can generate them easily. https://www.uuidgenerator.net/version4
global_access_keys = []

[cogs.Tags]
allowed_in_guilds = [
    1013868971549794415, # Discord Game Pass
]

[cogs.BotsListVoting]
statcord_token = "abcdef"

[random_ducks]
assets_path = 'assets/Random Ducks'
